# Generated by Django 2.2.1 on 2019-11-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_auto_20191101_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
